### ISSUE TITLE
Doesn't properly scale in compact mode (with other themes loaded)

### ISSUE THREAD

**Issue by Copperearth** [fluffingtons/revert-discord#1]
http://coppers.foreskin.market/product_images/da0fa6e6.png
This does not happen when loaded separately, the "black hole" theme was used to show this off.

**Comment by Copperearth** [comment]
https://i.imgur.com/SvwM4VE.png here is the picture again, but on a website that doesn't sound as much like an IP logger

**Comment by zzzmario** [comment]
> https://i.imgur.com/SvwM4VE.png here is the picture again, but on a website that doesn't sound as much like an IP logger

yo can you send me that custom uploader file? mario#9999

**Comment by ItsiAdam** [comment]
i dont CARE I DONT CARE I DONT CARE

**Comment by fluffingtons** [comment]
This theme generally won't work well with others that change the message styling. You can try remove the problematic styling or adjust it in either theme.
