### ISSUE TITLE
Partially broken embeds/reacts

### ISSUE THREAD

**Issue by minervamaga** [fluffingtons/revert-discord#2]
Today's update to Discord partially broke the theme; images, embeds, etc are all "center" aligned now, as well as reaction emotes.  The line spacing and other fixes continue to work as intended though.

**Comment by minervamaga** [comment]
Update - reactions might be completely broken as of today.  They are not appearing at all for me.

**Comment by fluffingtons** [comment]
This issue appears to only occur on Canary due to a minor update. I can't fix this on Canary without breaking stable.

**Comment by minervamaga** [comment]
Second update - the reactions were from something else, my bad!  But the images etc are still messed up.  Canary is...?

**Comment by fluffingtons** [comment]
Your version of Discord. What version does Discord say it is in the bottom left of the settings page?

**Comment by minervamaga** [comment]
Stable 55236 (52bd1b8) - is that correct?

**Comment by fluffingtons** [comment]
That is odd, I can only reproduce this issue on Canary.

**Comment by minervamaga** [comment]
A friend is also having the same issue, we can provide screenshots if you need them.

**Comment by fluffingtons** [comment]
Can you contact me on Discord?

**Comment by minervamaga** [comment]
Absolutely!  My username is the same on there: minervamaga#7344
