### ISSUE TITLE
2/27/20 new update centers images?

### ISSUE THREAD

**Issue by davyplatt** [fluffingtons/revert-discord#3]
New discord update shifts attachments and images slightly to the right, could be caused by new update
![image](https://user-images.githubusercontent.com/53351082/75426780-30ae0280-58fa-11ea-9a10-b9f7dd2c8e71.png)

**Comment by fluffingtons** [comment]
This issue appears to only occur on Canary due to a minor update. I can't fix this on Canary without breaking stable.

**Comment by fluffingtons** [comment]
The update has reached stable and I have pushed an update which should address any issues.
